java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/rpe/template-test-spring:latest'
  ingressHost: rpe-template-test-spring-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rpe
  environment:
