version: '2.1'

services:
  template-test-spring:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/rpe/template-test-spring
    ports:
      - $SERVER_PORT:$SERVER_PORT
